site_name: Kloud Koncepts
site_description: >-
  Learn DevOps on Cloud
site_author: Reyansh Kharga
repo_name: ReyanshKharga/eks-kubernetes-masterclass
repo_url: https://github.com/ReyanshKharga/eks-kubernetes-masterclass
strict: true

# Defeine TOC or order of website
nav:
  - Home: index.md
  - Kubernetes on EKS:
    - ./kubernetes-on-eks/index.md
    - Docker Fundamentals:
      - Introduction to Docker: ./kubernetes-on-eks/docker-fundamentals/introduction-to-docker.md
      - Install Docker: ./kubernetes-on-eks/docker-fundamentals/install-docker.md
      - Running Container From a Public Docker Image: ./kubernetes-on-eks/docker-fundamentals/run-container-from-public-image.md
      - Creating Docker Image: 
        - Customized Nginx Docker Image: ./kubernetes-on-eks/docker-fundamentals/customized-nginx-docker-image.md
        - Containerizing Node.js and Express App: ./kubernetes-on-eks/docker-fundamentals/nodejs-express-docker-image.md
      - Pushing Image to Docker Hub: ./kubernetes-on-eks/docker-fundamentals/push-image-to-docker-hub.md
    - YAML Fundamentals:
      - Introduction to YAML: ./kubernetes-on-eks/yaml-fundamentals/introduction-to-yaml.md
      - YAML Syntax and Structure: ./kubernetes-on-eks/yaml-fundamentals/yaml-syntax-and-structure.md
      - Data Types in YAML: ./kubernetes-on-eks/yaml-fundamentals/data-types-in-yaml.md
      - YAML Tools and Resources: ./kubernetes-on-eks/yaml-fundamentals/yaml-tools-and-resources.md
    - Kubernetes Overview and Architecture: 
      - Introduction to Kubernetes: ./kubernetes-on-eks/kubernetes-overview-and-architecture/introduction-to-kubernetes.md
      - Architecture of Kubernetes: ./kubernetes-on-eks/kubernetes-overview-and-architecture/kubernetes-architecture.md
    - Amazon EKS Overview and Architecture:
      - Introduction to Amazon EKS: ./kubernetes-on-eks/amazon-eks-overview-and-architecture/introduction-to-amazon-eks.md
      - Architecture of Amazon EKS: ./kubernetes-on-eks/amazon-eks-overview-and-architecture/eks-architecture.md
    - Install CLI Tools:
      - Introduction to CLI Tools: ./kubernetes-on-eks/install-cli-tools/introduction-to-cli-tools.md
      - Install and Configure AWS CLI: ./kubernetes-on-eks/install-cli-tools/install-and-configure-aws-cli.md
      - Install Kubectl: ./kubernetes-on-eks/install-cli-tools/install-kubectl.md
      - Install Eksctl: ./kubernetes-on-eks/install-cli-tools/install-eksctl.md
      - Install Helm CLI: ./kubernetes-on-eks/install-cli-tools/install-helm-cli.md
    - Create EKS Cluster:
      - Create EKS Cluster Using eksctl: ./kubernetes-on-eks/create-eks-cluster/create-eks-cluster.md
      - Verify Worker Nodes: ./kubernetes-on-eks/create-eks-cluster/verify-worker-nodes.md
      - VPC Resources Created by EKS: ./kubernetes-on-eks/create-eks-cluster/vpc-resources-created-by-eks.md
      # - 
      # -

# Plugins
plugins:
  - search
  # - privacy

# Extra
extra:
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback! Help us improve this page by
            using our <a href="..." target="_blank" rel="noopener">feedback form</a>.

# Theme
theme:
  name: material
  features:
    - navigation.tabs
    # - navigation.sections
    # - toc.integrate
    - navigation.top
    - content.code.copy
    - content.code.annotate
    - navigation.footer
  language: en
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/images/icons/logo_black.png
  logo: assets/images/icons/logo.png

extra:
  generator: false # Removes Made with Material for MkDocs from footer
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/ReyanshKharga
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ReyanshKharga
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/ReyanshKharga

extra_css:
  - stylesheets/extra.css
  - https://unpkg.com/material-components-web@latest/dist/material-components-web.min.css
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - pymdownx.tabbed:
      alternate_style: true
  - admonition
  - footnotes
  - attr_list
  - tables
  - toc:
      permalink: true
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde

copyright: |
  Copyright &copy; 2023-2024 <a href="https://github.com/ReyanshKharga"  target="_blank" rel="noopener">Kloud Koncepts</a>