# Site Details
site_name: Kloud Koncepts
site_description: >-
  Master Kubernetes and DevOps on Cloud
site_author: Reyansh Kharga
site_url: https://kloudkoncepts.com/
repo_name: ReyanshKharga/eks-kubernetes-masterclass
repo_url: https://github.com/ReyanshKharga/eks-kubernetes-masterclass
strict: true


# Defeine TOC or order of website
nav:
  - Home: index.md
  - Kubernetes on EKS:
    - Course Introduction: ./kubernetes-on-eks/index.md
    - Docker Fundamentals:
      - Introduction to Docker: ./kubernetes-on-eks/docker-fundamentals/introduction-to-docker.md
      - Install Docker: ./kubernetes-on-eks/docker-fundamentals/install-docker.md
      - Run Container From a Public Docker Image: ./kubernetes-on-eks/docker-fundamentals/run-container-from-public-image.md
      - Create Docker Image: 
        - Customized Nginx Docker Image: ./kubernetes-on-eks/docker-fundamentals/customized-nginx-docker-image.md
        - Containerizing Node.js and Express App: ./kubernetes-on-eks/docker-fundamentals/nodejs-express-docker-image.md
      - Push Image to Docker Hub: ./kubernetes-on-eks/docker-fundamentals/push-image-to-docker-hub.md
    - YAML Fundamentals:
      - Introduction to YAML: ./kubernetes-on-eks/yaml-fundamentals/introduction-to-yaml.md
      - YAML Syntax and Structure: ./kubernetes-on-eks/yaml-fundamentals/yaml-syntax-and-structure.md
      - Data Types in YAML: ./kubernetes-on-eks/yaml-fundamentals/data-types-in-yaml.md
      - YAML Tools and Resources: ./kubernetes-on-eks/yaml-fundamentals/yaml-tools-and-resources.md
      - Advanced Features in YAML: ./kubernetes-on-eks/yaml-fundamentals/advanced-yaml-features.md
    - Kubernetes Overview and Architecture: 
      - Introduction to Kubernetes: ./kubernetes-on-eks/kubernetes-overview-and-architecture/introduction-to-kubernetes.md
      - Architecture of Kubernetes: ./kubernetes-on-eks/kubernetes-overview-and-architecture/kubernetes-architecture.md
    - Amazon EKS Overview and Architecture:
      - Introduction to Amazon EKS: ./kubernetes-on-eks/amazon-eks-overview-and-architecture/introduction-to-amazon-eks.md
      - Architecture of Amazon EKS: ./kubernetes-on-eks/amazon-eks-overview-and-architecture/eks-architecture.md
    - Install CLI Tools:
      - Introduction to CLI Tools: ./kubernetes-on-eks/install-cli-tools/introduction-to-cli-tools.md
      - Install and Configure AWS CLI: ./kubernetes-on-eks/install-cli-tools/install-and-configure-aws-cli.md
      - Install Kubectl: ./kubernetes-on-eks/install-cli-tools/install-kubectl.md
      - Install Eksctl: ./kubernetes-on-eks/install-cli-tools/install-eksctl.md
      - Install Helm CLI: ./kubernetes-on-eks/install-cli-tools/install-helm-cli.md
    - Create EKS Cluster:
      - Create EKS Cluster Using eksctl: ./kubernetes-on-eks/create-eks-cluster/create-eks-cluster.md
      - Verify Worker Nodes: ./kubernetes-on-eks/create-eks-cluster/verify-worker-nodes.md
      - VPC Resources Created by EKS: ./kubernetes-on-eks/create-eks-cluster/vpc-resources-created-by-eksctl.md
      - Delete EKS Cluster: ./kubernetes-on-eks/create-eks-cluster/delete-eks-cluster.md
    - Kubernetes Fundamentals:
      - Pod:
        - Introduction to Pod: ./kubernetes-on-eks/kubernetes-fundamentals/pod/introduction-to-pod.md
        - Imperative vs Declarative Approach: ./kubernetes-on-eks/kubernetes-fundamentals/pod/imperative-vs-declarative-approach.md
        - Pod Using Imperative Approach: ./kubernetes-on-eks/kubernetes-fundamentals/pod/pod-using-imperative-approach.md
        - Pod Using Declarative Approach: ./kubernetes-on-eks/kubernetes-fundamentals/pod/pod-using-declarative-approach.md
        - Busybox Pod: ./kubernetes-on-eks/kubernetes-fundamentals/pod/busybox-pod.md
        - Pod With Labels: ./kubernetes-on-eks/kubernetes-fundamentals/pod/pod-with-labels.md
      - ReplicaSet:
        - Introduction to ReplicaSet: ./kubernetes-on-eks/kubernetes-fundamentals/replicaset/introduction-to-replicaset.md
        - Create ReplicaSet: ./kubernetes-on-eks/kubernetes-fundamentals/replicaset/create-replicaset.md
        - How Does ReplicaSet Manage Pods?: ./kubernetes-on-eks/kubernetes-fundamentals/replicaset/how-does-replicaset-manage-pods.md
        - Challenges With ReplicaSets: ./kubernetes-on-eks/kubernetes-fundamentals/replicaset/challenges-with-replicasets.md
      - Deployment:
        - Introduction to Deployment: ./kubernetes-on-eks/kubernetes-fundamentals/deployment/introduction-to-deployment.md
        - Deployment Using Imperative Approach: ./kubernetes-on-eks/kubernetes-fundamentals/deployment/deployment-using-imperative-approach.md
        - Scale a Deployment: ./kubernetes-on-eks/kubernetes-fundamentals/deployment/scale-deployment.md
        - Update a Deployment: ./kubernetes-on-eks/kubernetes-fundamentals/deployment/update-deployment.md
        - Rollback a Deployment: ./kubernetes-on-eks/kubernetes-fundamentals/deployment/rollback-deployment.md
        - Deployment Using Declarative Approach: ./kubernetes-on-eks/kubernetes-fundamentals/deployment/deployment-using-declarative-approach.md
        - Pause and Resume a Deployment: ./kubernetes-on-eks/kubernetes-fundamentals/deployment/pause-and-resume-deployment.md
      - Service:
        - Access Pods Without Service: ./kubernetes-on-eks/kubernetes-fundamentals/service/access-pods-without-service.md
        - Introduction to Service: ./kubernetes-on-eks/kubernetes-fundamentals/service/introduction-to-service.md
        - Kubernetes Service Types: ./kubernetes-on-eks/kubernetes-fundamentals/service/service-types.md
        - Exposure Level of Different Service Types: ./kubernetes-on-eks/kubernetes-fundamentals/service/exposure-level-of-service-types.md
        - Create Service: ./kubernetes-on-eks/kubernetes-fundamentals/service/create-service.md
        - Role of Selector in Service: ./kubernetes-on-eks/kubernetes-fundamentals/service/role-of-selector-in-service.md
        # -
        # -
        # -
        # -
        # -
        # -
  - DevOps & SRE Interview Questions:
      - ./devops-and-sre-interview-questions/index.md
      - Networking: ./devops-and-sre-interview-questions/networking.md


# Plugins
plugins:
  - search
  - minify:
      minify_html: true
      minify_js: true
      minify_css: true


# Theme
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.top
    - content.code.copy
    - content.code.annotate
    - navigation.footer
  language: en
  palette:
    - scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/images/icons/logo_black.png
  logo: assets/images/icons/logo.png


# Extra
extra:
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >- 
            Thanks for your feedback!
  generator: false # Removes Made with Material for MkDocs from footer
  status:
    new: Recently added
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/ReyanshKharga
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ReyanshKharga
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/ReyanshKharga


extra_css:
  - stylesheets/extra.css
  - https://unpkg.com/material-components-web@latest/dist/material-components-web.min.css


extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


markdown_extensions:
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - admonition
  - footnotes
  - attr_list
  - tables
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - toc:
      permalink: true
  


copyright: |
  Copyright &copy; 2023-2024 <a href="https://github.com/ReyanshKharga"  target="_blank" rel="noopener">Kloud Koncepts</a>