# Project information
site_name: kloudkoncepts - Learn Kubernetes with Examples
# defeine TOC or order of website-
nav:
  - Home: index.md
  - Pod: pod.md

site_author: Reyansh Kharga
site_description: >-
  Learn Kubernetes with Examples.

# Repository
repo_name: ReyanshKharga/eks-kubernetes-masterclass
repo_url: https://github.com/ReyanshKharga/eks-kubernetes-masterclass

# Configuration
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
  language: en
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  favicon: images/logo_black.png
  logo: assets/logo.png

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/ReyanshKharga
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ReyanshKharga
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/ReyanshKharga

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js #?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  
  
plugins:
  - search

copyright: |
  &copy; 2023 <a href="https://github.com/ReyanshKharga"  target="_blank" rel="noopener">Reyansh Kharga</a>